Login://input[@placeholder='pat@example.com']
Password://input[@type='password']
Submit://button[@type='submit']
Logo://img[@alt='logo']
WelcomeTest://h1[normalize-space()='Welcome, Ankita Saxena!']
Balance://div[@class='d-flex align-items-center balance-clr ng-star-inserted']
Home:(//li[@class='ps-3 nav-menu-profile active'])[1]
Teams:(//div[@class='d-flex align-items-center'][normalize-space()='Team'])[1]
AddMember:(//button[@class='rounded-sm omni-btn ng-star-inserted'][normalize-space()='Add Member'])[1]
MobileNumber:(//input[@id='mat-input-2'])[1]
EmailId:(//input[@id='mat-input-6'])[1]
FirstName:(//input[@id='mat-input-3'])[1]
LastName:(//input[@id='mat-input-4'])[1]
EmployeeId:(//input[@id='mat-input-5'])[1]
SelectStore:(//span[@class='dropdown-multiselect__caret'])[4]
Store:(//div[@class='ng-star-inserted'][normalize-space()='PNQ Shivaji Nagar'])[2]
SelectDepartment:(//span[@class='dropdown-multiselect__caret'])[5]
DepartmentQA:(//div[@class='ng-star-inserted'][normalize-space()='Quality Analyst'])[2]
AddMemberSubmit:(//button[normalize-space()='Submit'])[1]
EmailId:mat-input-6
RespMsg:(//small[@class='text-danger text-center errTexts ng-star-inserted'])[1]
SearchMob:(//input[@id='mat-input-0'])[1]
NoData:(//p[@class='pt-4'][normalize-space()='No data found'])[1]
MasterTeamDownloadTeams:(//img[@alt='download'])[1]
MasterTeamDownloadReports:(//img[@class='img-fluid'])[4]
CardInTeams://tbody/tr[1]/td[6]/span[1]
AddCard:(//button[@class='rounded-sm omni-btn web-hide ng-star-inserted'])[1]
CardName:(//input[@id='mat-input-2'])[1]
AddCardProceed:(//button[normalize-space()='Proceed'])[1]
EditTeamMember:(//img[@title='Edit'])[1]
FName:(//input[@id='mat-input-5'])[1]
EditSubmit:(//button[normalize-space()='Submit'])[1]
Updated:(//button[normalize-space()='Updated'])[1]
BackToTeams:(//img[@class='cPointer'])[1]
MisTab:(//div[contains(text(),'MIS')])[1]
SearchMobileNumber:mat-input-1
SearchempId:mat-input-2
SearchTrxnId:mat-input-0
SearchStartDate:(//button[normalize-space()='Dates'])[1]
SearchLastMonth:(//button[normalize-space()='This Month'])[1]
SearchSelect:(//button[normalize-space()='Select'])[1]
TrxnSubmit:(//button[normalize-space()='Submit'])[1]
TrxnTable:(//td[@scope='col'])[1]
TrxnAllTab:(//li[normalize-space()='Transaction Report-All'])[1]